services:
  whisperx-api:
    container_name: whisperx-api-gpu
    image: cybert/whisperx-api:gpu
    pull_policy: never
    restart: unless-stopped
    ports:
      - "8097:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./whisper_models:/app/wx_models
      - ./hf_cache:/app_cache
    environment:
      NVIDIA_VISIBLE_DEVICES: "1"
      WHISPER_MODELS: tiny,small
      UPLOAD_DIR: /app/uploads
      WHISPER_MODELS_DIR: /app/wx_models
      HF_HOME: /app_cache
      WHISPER_THREADS: 2
      WHISPER_DEVICE: cuda
      WHISPER_HF_TOKEN: $WHISPER_HF_TOKEN
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
